<h2 align="center">
    Week 9
</h2>
<div>
    <h3>Author: Iqbal Ramadhan</h3>
    <h3>ID Student:21083010111</h3>
    <h3>Subject:Computational statistics<h3>
    <h4>Link For this source :<br><a>https://github.com/kayabaakihiko13/computation_of_statics/tree/main/Week7/Task/a></h4>
</div>

<h1 align="center">Jackknife</h1>

<h5>Dalam statistik, jackknife adalah teknik validasi silang dan, karenanya, merupakan bentuk resampling. Ini sangat berguna untuk estimasi bias dan varians. Jackknife mendahului metode resampling umum lainnya seperti <a href="https://en.wikipedia.org/wiki/Bootstrapping_(statistics)">bootstrap</a>
</h5>

> refences:https:
https://en.wikipedia.org/wiki/Jackknife_resampling


In [1]:
from model.nerve import jackknife_stat
from model.basic import mean

In [4]:
# sample for jackknife
sample = ([7, 11, 8, 30])
# jackknife_stat(sample,np.mean)

In [3]:
jackknife_stat(sample,mean)

(array([[11.,  8., 30.],
        [ 7.,  8., 30.],
        [ 7., 11., 30.],
        [ 7., 11.,  8.]]),
 14.000000000000005,
 -5.329070518200751e-15,
 5.400617248673217,
 array([ 3.4149847, 24.5850153]))

In [4]:
import numpy as np
jackknife_stat(sample,np.mean)

(array([[11.,  8., 30.],
        [ 7.,  8., 30.],
        [ 7., 11., 30.],
        [ 7., 11.,  8.]]),
 14.000000000000005,
 -5.329070518200751e-15,
 5.400617248673217,
 array([ 3.4149847, 24.5850153]))

In [5]:
resample,mean_resample,_,_,_=jackknife_stat(sample,mean)
resample
# mean(resample)
mean_resample

14.000000000000005

In [3]:
import numpy as np
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



In [10]:
np.shape(sample)[0]

4